/*
 * nes_core_java_shim.c - C ABI shim for the GraalVM Native Image shared
 * library nes_core_java.dll.
 *
 * Exports the 13 nes_core_* symbols defined in cores/protocol.h with the
 * EXACT protocol.h signatures (no graal_isolatethread_t* first param).
 * Manages a single global graal isolate lazily on first use and forwards
 * each call to the corresponding java_* @CEntryPoint generated by
 * native-image --shared. Linked into the same DLL via:
 *   native-image --shared ... -H:NativeLinkerOption=nes_core_java_shim.obj
 *
 * The opaque nes_core_t handle is a pointer-sized integer key into the Java
 * handle registry (HashMap<Integer, Emulator>). nes_core_create returns
 * (nes_core_t*)(uintptr_t)javaLongHandle; 0 maps to NULL.
 */
/* protocol.h types — declared inline to avoid linkage conflicts with
 * __declspec(dllexport) on the function definitions below. */
typedef struct nes_core_t nes_core_t;  /* opaque */

#include "nes_core_java.h"    /* generated by native-image --shared (java_* decls) */
#include "graal_isolate.h"    /* generated by native-image --shared (isolate API) */
#include <stdint.h>
#include <stddef.h>

/* ---- Global isolate (one per process — the harness loads one core at a time) ---- */
static graal_isolate_t* g_isolate = NULL;
static graal_isolatethread_t* g_thread = NULL;

static graal_isolatethread_t* get_thread(void) {
    if (g_thread) return g_thread;
    if (!g_isolate) {
        if (graal_create_isolate(NULL, &g_isolate, &g_thread) != 0) return NULL;
    } else {
        if (graal_attach_thread(g_isolate, &g_thread) != 0) return NULL;
    }
    return g_thread;
}

/* Handle conversion: nes_core_t* <-> java long handle.
 * 0 (NULL) is the universal "invalid" sentinel. */
static nes_core_t* handle_to_ptr(long h) {
    return (h == 0) ? NULL : (nes_core_t*)(uintptr_t)h;
}
static long ptr_to_handle(nes_core_t* core) {
    return (long)(uintptr_t)core;
}

/* ---- Lifecycle ------------------------------------------------------- */

__declspec(dllexport)
nes_core_t* nes_core_create(const uint8_t* rom_data, size_t rom_len) {
    graal_isolatethread_t* t = get_thread();
    if (!t) return NULL;
    if (!rom_data || rom_len == 0) return NULL;
    void* h = java_create(t, (char*)rom_data, (size_t)rom_len);
    return (nes_core_t*)h;  /* 0 -> NULL already handled by Java side */
}

__declspec(dllexport)
void nes_core_destroy(nes_core_t* core) {
    graal_isolatethread_t* t = get_thread();
    if (!t || !core) return;
    java_destroy(t, (void*)core);
}

__declspec(dllexport)
void nes_core_reset(nes_core_t* core) {
    graal_isolatethread_t* t = get_thread();
    if (!t || !core) return;
    java_reset(t, (void*)core);
}

__declspec(dllexport)
int nes_core_set_region(nes_core_t* core, int region) {
    graal_isolatethread_t* t = get_thread();
    if (!t) return -1;
    if (!core) return -1;
    return java_set_region(t, (void*)core, region);
}

/* ---- Stepping -------------------------------------------------------- */

__declspec(dllexport)
uint32_t nes_core_step_frame(nes_core_t* core) {
    graal_isolatethread_t* t = get_thread();
    if (!t || !core) return 0u;
    return (uint32_t)java_step_frame(t, (void*)core);
}

__declspec(dllexport)
uint32_t nes_core_step_instruction(nes_core_t* core) {
    graal_isolatethread_t* t = get_thread();
    if (!t || !core) return 0u;
    return (uint32_t)java_step_instruction(t, (void*)core);
}

/* ---- Output ---------------------------------------------------------- */

__declspec(dllexport)
const uint32_t* nes_core_framebuffer(nes_core_t* core) {
    graal_isolatethread_t* t = get_thread();
    if (!t || !core) return NULL;
    return (const uint32_t*)java_framebuffer(t, (void*)core);
}

__declspec(dllexport)
size_t nes_core_take_audio(nes_core_t* core, int16_t* buf, size_t cap) {
    graal_isolatethread_t* t = get_thread();
    if (!t || !core || !buf || cap == 0) return 0u;
    return java_take_audio(t, (void*)core, (short*)buf, (size_t)cap);
}

/* ---- Save state ------------------------------------------------------ */

__declspec(dllexport)
size_t nes_core_save_state(nes_core_t* core, uint8_t* buf, size_t cap) {
    graal_isolatethread_t* t = get_thread();
    if (!t || !core || !buf || cap == 0) return 0u;
    return java_save_state(t, (void*)core, (char*)buf, (size_t)cap);
}

__declspec(dllexport)
int nes_core_load_state(nes_core_t* core, const uint8_t* buf, size_t len) {
    graal_isolatethread_t* t = get_thread();
    if (!t || !core || !buf || len == 0) return 0;
    return java_load_state(t, (void*)core, (char*)buf, (size_t)len);
}

/* ---- Introspection --------------------------------------------------- */

__declspec(dllexport)
uint16_t nes_core_mapper_number(nes_core_t* core) {
    graal_isolatethread_t* t = get_thread();
    if (!t || !core) return 0u;
    return (uint16_t)java_mapper_number(t, (void*)core);
}

__declspec(dllexport)
const char* nes_core_impl_name(void) {
    graal_isolatethread_t* t = get_thread();
    if (!t) return "java-nes";
    return java_impl_name(t);
}

__declspec(dllexport)
const char* nes_core_impl_version(void) {
    graal_isolatethread_t* t = get_thread();
    if (!t) return "0.1.0";
    return java_impl_version(t);
}
