audio_volume = 1.0
window_scale = 3
region = "auto"
recent_roms = [
    '.\tests\real_roms\Mega-Man.NES',
    '.\tests\real_roms\MarioBros.NES',
    'C:\Users\W4RHEAD\Documents\PROJECTS\TOKENCRAPPING\NES-EMU\tests\real_roms\Zelda.NES',
    'C:\Users\W4RHEAD\Documents\Downloads\MarioBros.NES',
    'C:\Users\W4RHEAD\Documents\Downloads\Mega-Man.NES',
]
rewind_capacity = 3000
turbo_speed = 4.0
rewind_branching = true
timeline_enabled = true
countdown_delay_ms = 500
countdown_start_number = 2

[keys.controller1]
A = "L"
B = "K"
Down = "S"
Left = "A"
Right = "D"
Select = "H"
Start = "G"
Up = "W"

[keys.controller2]

[gamepad]
A = "a"
B = "b"
Down = "dpdown"
Left = "dpleft"
Right = "dpright"
Select = "back"
Start = "start"
Up = "dpup"

[audio_channels]
pulse1 = 1.0
pulse2 = 1.0
triangle = 1.0
noise = 1.0
dmc = 1.0

[debug]
slant_corruption = false
ring_buffer_trace = false
use_inaccurate_palette = false
nmi_retrigger = false
